name: tests

on:
  pull_request:
    branches: [master, develop, squall_integration]

  push:
    branches: [master, develop, squall_integration]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout changes
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2

    - name: Install dependencies
      run: |
        find frameworks | grep requirements.txt | xargs -n 1 pip install -r
        pip install pytest pytest-aio janus

    - name: Test with pytest
      run: |
        pytest frameworks
